packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - astro@6.3.8
  - '@sanity/diff@5.27.0'
  - '@sanity/mutator@5.27.0'
  - '@sanity/schema@5.27.0'
  - '@sanity/types@5.27.0'
  - '@sanity/util@5.27.0'
  - '@sanity/vision@5.27.0'
  - sanity@5.27.0
